### ISSUE TITLE
Exploração de Dados

### ISSUE THREAD

**Issue by felinjob** [vikpires/avanti-bootcamp-cdd#2]
A equipe deve criar um notebook de análise exploratória **notebooks/01-exploratory_data_analysis.ipynb**, contendo as seguintes seções de texto:

- [x]  **Descrição dos dados:** informações sobre a quantidade de instâncias, variáveis e seus tipos, quantidade de valores faltantes. Utilize o dicionário de dados nessa seção.
- [x]  **Perguntas de partida e hipóteses:** que tipo de informações podem ser obtidas a partir dos dados e quais hipóteses podem ser levantadas?
- [x]  **Insights:** respostas às perguntas feitas na seção anterior e quais informações interessantes podem ser levantadas através dos dados?

**Comment by felinjob** [comment]
A análise exploratória foi realizada com sucesso e atende todos os requisitos propostos.
Sugiro pequenas otimizações no notebook para aprimorar a legibilidade e organização do código, sem impactar os resultados da análise. 

1. Apesar do tema escolhido ser o "ticks", ele não se aplica a todas as células, que variam entre ele e o whitegrid.
![Screenshot from 2024-07-29 14-44-20-1](https://github.com/user-attachments/assets/1cc8624b-fdf2-493b-8f41-22a2339ce7b4)

2. Sugiro a inserção de uma condicional if/else na célula que busca dados faltantes, para ajustar a concordância no texto do print.
![Screenshot from 2024-07-29 13-51-53](https://github.com/user-attachments/assets/ccbc8fc3-3867-4a80-8f19-7d7126a96cb9)

3. Otimizar o código na célula que busca valores únicos, utilizando um set no lugar da lista dentro da variável "uniques".
![Screenshot from 2024-07-29 13-52-54](https://github.com/user-attachments/assets/b062f6ee-83d1-4a91-a147-1ed8bf9b46d0)

4. Arredondar os valores na colula tip_rate_(%) para duas casas decimais.
![Screenshot from 2024-07-29 13-57-19](https://github.com/user-attachments/assets/e7c587e0-cabc-48ce-810b-4d0c3e0ebf3e)

**Comment by vikpires** [comment]
Enviei o arquivo com os devidos ajustes 👍

**Comment by felinjob** [comment]
Todas as alterações propostas foram bem executadas.
